[package]
name = "repro"
version = "0.1.0"
authors = ["lqd"]
edition = "2018"

[dependencies]
chrono = "*"
dotenv = "*"
futures = "*"
hyper = "*"
juniper = "*"
juniper_hyper = "*"
log="*"
uuid="*"
pretty_env_logger = "0.3"